server:
  port: 8001
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  codec:
    max-in-memory-size: 20MB

springdoc:
  packages-to-scan: co.vuckovic.aicodereviewev.controllers
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

swagger-ui:
  server-prod: http://localhost:8001
  server-dev: http://localhost:8001



scheduler:
  period: 5000