style-checking:
  check-style: "Check code styling of the following code and output only the important notes. Output should be in the following format: Line <number>: <Rate the importance of the check from 1 to 5, 1 has least importance and 5 has highest importance>: <Description> \n\n"
